# Generated by Django 4.0.3 on 2022-03-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draws',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('n1', models.IntegerField(blank=True, null=True)),
                ('n2', models.IntegerField(blank=True, null=True)),
                ('n3', models.IntegerField(blank=True, null=True)),
                ('n4', models.IntegerField(blank=True, null=True)),
                ('n5', models.IntegerField(blank=True, null=True)),
                ('n6', models.IntegerField(blank=True, null=True)),
                ('n7', models.IntegerField(blank=True, null=True)),
                ('n8', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
